# Categories of the generated release notes (gh release create --generate-notes)
changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Everything else
      labels:
        - '*'
