import type {Metadata} from "next";
import {cookies} from "next/headers";
import {Geist, Geist_Mono} from "next/font/google";
import React from "react";
import {Provider} from "@/components/Provider";
import {ThemeE} from "@/types/common";
import {getThemeLink} from "@/helpers/getThemeLink";
import styles from "./styles.module.css";
import "./globals.css";
import 'primeicons/primeicons.css';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vocab Bloom Admin panel",
    description: "Generated by create next app",
};

type RootLayoutP = Readonly<{
    children: React.ReactNode;
}>

export default async function RootLayout({children}: RootLayoutP) {
    const isAuth = false;
    const cookieStore = await cookies()
    const theme = (cookieStore.get('theme')?.value || ThemeE.light) as ThemeE;
    const themeLink = getThemeLink(theme);

    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <head>
            <link id="theme-link" rel="stylesheet" href={themeLink}/>
        </head>
        <body>
        <Provider isAuth={isAuth}>
            <main className={styles.mainContainer}>
                {children}
            </main>
        </Provider>
        </body>
        </html>
    );
}
