// Headwords shown on the word index and listed in the sitemap: common,
// polysemous, with phrasal verbs and every part of speech among them
export const EXAMPLE_WORDS = [
  'run',
  'take',
  'get',
  'look',
  'set',
  'make',
  'light',
  'give up',
  'look forward to',
  'bank',
  'fast',
  'well',
  'book',
  'bear',
  'fine',
  'kind',
  'lead',
  'match',
  'point',
  'rose',
];
