export enum ErrorCodes {
  login_or_pass_wrong = 'login_or_pass_wrong',
  invalid_token = 'invalid_token',
  internal_server_error = 'Internal server error',
  unparsed_data = 'unparsed_data',
  failed_fetch = 'failed_fetch',
  word_already_exists = 'word_already_exists',
  phrasal_base_doesnt_exist = 'phrasal_base_doesnt_exist',
  word_doesnt_found = 'word_doesnt_found',
  synonym_doesnt_exist = 'synonym_doesnt_exist',
  antonym_doesnt_exist = 'antonym_doesnt_exist',
  synonym_antonym_conflict = 'synonym_antonym_conflict',
  dataset_manifest_not_found = 'dataset_manifest_not_found',
  // local dataset sources (issue #269)
  import_dir_not_configured = 'import_dir_not_configured',
  dataset_file_not_found = 'dataset_file_not_found',
  dataset_invalid = 'dataset_invalid',
  dataset_upload_missing = 'dataset_upload_missing',
  // one import at a time (issue #268)
  import_in_progress = 'import_in_progress',
  // several datasets per instance (issue #527)
  // the database driver has no schemas (SQLite): one dataset, no switching
  datasets_not_supported = 'datasets_not_supported',
  dataset_not_found = 'dataset_not_found',
  // the name is not one of the catalog of datasets
  dataset_name_invalid = 'dataset_name_invalid',
  // the active dataset cannot be deleted, nor the one the instance was born with
  dataset_is_active = 'dataset_is_active',
  dataset_is_default = 'dataset_is_default',
  // another dataset is being created, activated or deleted right now
  datasets_busy = 'datasets_busy',
  // datasets are never mixed: the data names another source than the dataset it would go into
  dataset_source_mismatch = 'dataset_source_mismatch',
  // the attached file is not what the source of the dataset distributes
  dataset_source_invalid = 'dataset_source_invalid',
  // the dataset is installed through the import page, not from a source file
  dataset_not_installable = 'dataset_not_installable',
  // a dataset of the instance's own (issue #540): the name is one the catalog uses, as a dataset or as a source
  dataset_name_reserved = 'dataset_name_reserved',
  dataset_already_exists = 'dataset_already_exists',
  // the terms of a dataset of the catalog are the catalog's: nothing about them is edited
  dataset_terms_fixed = 'dataset_terms_fixed',
  // neither a license of the list nor a complete license of the owner's own
  dataset_license_invalid = 'dataset_license_invalid',
  // a dataset of a public source holds what people wrote: nothing generated by a model goes into it
  generated_not_allowed = 'generated_not_allowed',
  // the history of edits (issue #531)
  change_doesnt_found = 'change_doesnt_found',
  // the change no longer shows in what is served, or its values were never recorded
  change_not_revertible = 'change_not_revertible',
  // what the change left was edited again, or is gone: later changes are taken back first
  change_outdated = 'change_outdated',
  translation_doesnt_found = 'translation_doesnt_found',
  setting_field_doesnt_found = 'setting_field_doesnt_found',
  setting_field_already_exists = 'setting_field_already_exists',
  unknown_error = 'unknown_error',
  too_many_requests = 'too_many_requests',
  // reader feedback on the dictionary data (issue #327)
  suggestion_doesnt_found = 'suggestion_doesnt_found',
  suggestion_queue_full = 'suggestion_queue_full',
  // the proposed changes are malformed: unknown field, wrong type, nothing changed
  suggestion_invalid = 'suggestion_invalid',
  // apply on a report, or on a suggestion that already took a verdict
  suggestion_not_applicable = 'suggestion_not_applicable',
  // public list paging (issue #272)
  invalid_cursor = 'invalid_cursor',
  // the public OpenAPI document was not attached to the application (issue #273)
  openapi_not_available = 'openapi_not_available',
}
