export enum ErrorCodes {
  login_or_pass_wrong = 'login_or_pass_wrong',
  invalid_token = 'invalid_token',
  internal_server_error = 'Internal server error',
  unparsed_data = 'unparsed_data',
  failed_fetch = 'failed_fetch',
  word_already_exists = 'word_already_exists',
  phrasal_base_doesnt_exist = 'phrasal_base_doesnt_exist',
  word_doesnt_found = 'word_doesnt_found',
  synonym_doesnt_exist = 'synonym_doesnt_exist',
  dataset_manifest_not_found = 'dataset_manifest_not_found',
  translation_doesnt_found = 'translation_doesnt_found',
  setting_field_doesnt_found = 'setting_field_doesnt_found',
  setting_field_already_exists = 'setting_field_already_exists',
  unknown_error = 'unknown_error',
  too_many_requests = 'too_many_requests',
}
