import type {Metadata} from "next";
import {LoginForm} from "@/app/[locale]/login/_components/LoginForm";
import styles from './styles.module.scss'

export const metadata: Metadata = {
    title: "Login to Vocab Bloom Admin panel",
    description: "Generated by create next app",
};

export default function LoginPage () {
    return <div className={styles.loginPage}>
        <LoginForm/>
    </div>
}