import type {Metadata} from "next";
import { Button } from 'primereact/button';
import {InputText} from "primereact/inputtext";
import {LoginHeader} from "./_components/LoginHeader";
import {LoginFooter} from "./_components/LoginFooter";
import styles from './styles.module.scss'

export const metadata: Metadata = {
    title: "Login to Vocab Bloom Admin panel",
    description: "Generated by create next app",
};

export default function LoginPage () {
    return <div className={styles.loginPage}>
        <div className={styles.loginContent}>
            <LoginHeader/>
            <div className={styles.card}>
                <h1>Vocab Bloom</h1>
                <h2>Admin panel</h2>
                <InputText id="username" placeholder="Username" />
                <InputText id="password" placeholder="Password" />
                <Button label="Submit" />
            </div>
            <LoginFooter/>
        </div>
    </div>
}