import React from 'react';
import type { Metadata } from 'next';
import { SideMenu } from '@/components/SideMenu';
import styles from './styles.module.scss';

export const metadata: Metadata = {
  title: 'Vocab Bloom Admin panel',
  description: 'Generated by create next app',
};

type RootLayoutP = Readonly<{
  children: React.ReactNode;
}>;

export default async function RootLayout({ children }: RootLayoutP) {
  return (
    <>
      <SideMenu />
      <div className={styles.mainContent}>{children}</div>
    </>
  );
}
