// Generate only the requested clients' local configuration. See docs/agents.md.
import { constants, copyFileSync, lstatSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const paths = {
  codex: '.codex/config.toml',
  claude: '.mcp.json',
  cursor: '.cursor/mcp.json',
  gemini: '.gemini/settings.json',
  copilot: '.vscode/mcp.json',
  kiro: '.kiro/settings/mcp.json',
  amp: '.amp/settings.json',
  opencode: 'opencode.json',
};
const usage = `Usage: yarn agents:setup <agent> [<agent> ...] [--force]
Agents: ${Object.keys(paths).join(', ')}
--force  Back up differing files before replacing them.
--help   Show this help without writing files.
See docs/agents.md for setup and local overrides.\n`;

function render(agent, config) {
  const servers = (convert) =>
    Object.fromEntries(Object.entries(config.mcpServers).map(([name, server]) => [name, convert(server)]));
  const stdio = ({ command, args }) => ({ command, args });
  const typedStdio = (server) => ({ type: 'stdio', ...stdio(server) });
  const tomlFields = (fields) =>
    Object.entries(fields)
      .map(([key, value]) => `${key} = ${JSON.stringify(value)}`)
      .join('\n');

  if (agent === 'codex') {
    return (
      '# Generated by yarn agents:setup codex. Source: .agents/config.json; see docs/agents.md.\n\n' +
      [
        tomlFields(config.codex),
        ...Object.entries(config.mcpServers).map(
          ([name, server]) => `[mcp_servers.${JSON.stringify(name)}]\n${tomlFields(server)}`,
        ),
      ].join('\n\n') +
      '\n'
    );
  }

  const configs = {
    claude: { mcpServers: servers(typedStdio) },
    cursor: { mcpServers: servers(stdio) },
    gemini: { ...config.gemini, mcpServers: servers(stdio) },
    copilot: { servers: servers(typedStdio) },
    kiro: { mcpServers: servers(stdio) },
    amp: { 'amp.mcpServers': servers(stdio) },
    opencode: {
      $schema: 'https://opencode.ai/config.json',
      mcp: servers(({ command, args }) => ({ type: 'local', command: [command, ...args], enabled: true })),
    },
  };
  return JSON.stringify(configs[agent], null, 2) + '\n';
}

function statIfPresent(path) {
  try {
    return lstatSync(path);
  } catch (error) {
    if (error.code === 'ENOENT') return undefined;
    throw error;
  }
}

function readExisting(relativePath) {
  // Never follow a client's symlink into a global config, even with --force.
  const path = join(root, relativePath);
  for (let current = path; current !== resolve(root); current = dirname(current)) {
    if (statIfPresent(current)?.isSymbolicLink()) {
      throw new Error(`Refusing to write through a symbolic link: ${relativePath}`);
    }
  }
  if (!statIfPresent(path)) return undefined;
  return readFileSync(path, 'utf8');
}

function backup(path) {
  for (let index = 0; ; index++) {
    const target = `${path}.bak${index ? `.${index}` : ''}`;
    try {
      copyFileSync(path, target, constants.COPYFILE_EXCL);
      return target;
    } catch (error) {
      if (error.code !== 'EEXIST') throw error;
    }
  }
}

function main(args) {
  if (args.length === 0 || (args.length === 1 && args[0] === '--help')) {
    process.stdout.write(usage);
    return;
  }
  const force = args.includes('--force');
  const agents = [...new Set(args.filter((arg) => arg !== '--force'))];
  const unknown = agents.filter((agent) => !Object.hasOwn(paths, agent));
  if (unknown.length || !agents.length) {
    throw new Error(
      `Choose one or more supported agents.${unknown.length ? ` Unknown: ${unknown.join(', ')}.` : ''}\n${usage}`,
    );
  }
  const config = JSON.parse(readFileSync(join(root, '.agents/config.json'), 'utf8'));
  // Read every target first: a conflict must not leave a partially configured set.
  const files = agents.map((agent) => ({
    path: paths[agent],
    content: render(agent, config),
    existing: readExisting(paths[agent]),
  }));
  const conflicts = files.filter(({ content, existing }) => existing !== undefined && existing !== content);
  if (conflicts.length && !force) {
    throw new Error(
      `Existing configuration differs: ${conflicts.map(({ path }) => path).join(', ')}.\n` +
        'No files changed. Review it, then use --force to back it up and replace it.',
    );
  }
  for (const { path, content, existing } of files) {
    if (existing === content) {
      process.stdout.write(`Unchanged: ${path}\n`);
      continue;
    }
    if (existing !== undefined) {
      const saved = backup(join(root, path));
      process.stdout.write(`Backup: ${saved}\n`);
    }
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), content, { flag: existing === undefined ? 'wx' : 'w' });
    process.stdout.write(`Configured: ${path}\n`);
  }
}

try {
  main(process.argv.slice(2));
} catch (error) {
  process.stderr.write(`${error.message}\n`);
  process.exitCode = 1;
}
