import type {Metadata} from "next";
import {cookies} from "next/headers";
import {Geist, Geist_Mono} from "next/font/google";
import React from "react";
import {notFound} from "next/navigation";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from 'next-intl';
import {routing} from '@/i18n/routing';
import {Provider} from "@/components/Provider";
import {InterfaceLanguageEnum, ThemeE} from "@/types/common";
import {getThemeLink} from "@/helpers/getThemeLink";
import {ServerAuthApi} from "@/core/api/AuthApi/ServerAuthApi";
import styles from "./styles.module.css";
import "./globals.css";
import 'primeicons/primeicons.css';
import {Footer} from "@/components/Footer";
import {Header} from "@/components/Header";
import {SideMenu} from "@/components/SideMenu";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vocab Bloom Admin panel",
    description: "Generated by create next app",
};

type RootLayoutP = Readonly<{
    children: React.ReactNode;
    params: Promise<{
        locale: InterfaceLanguageEnum;
    }>
}>

export default async function RootLayout({children, params}: RootLayoutP) {
    const {locale} = await params;

    if (!routing.locales.includes(locale as any)) notFound();
    const messages = await getMessages();

    const isValidTokenRes = await ServerAuthApi.checkToken();
    const isAuth = isValidTokenRes.isValid;
    const cookieStore = await cookies()
    const theme = (cookieStore.get('theme')?.value || ThemeE.light) as ThemeE;
    const themeLink = getThemeLink(theme);
    return (
        <html lang={locale} className={`${geistSans.variable} ${geistMono.variable}`}>
        <head>
            <link id="theme-link" rel="stylesheet" href={themeLink}/>
        </head>
        <body>
        <NextIntlClientProvider messages={messages}>
            <Header/>
            <main className={styles.mainContainer}>
                <Provider isAuth={isAuth}>
                    {children}
                </Provider>
            </main>
            <Footer/>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
