'use client';

import { CopyWordPicker, CopyPreviewT } from '@/components/Origins/CopyWordPicker';
import { OriginsEditor } from '@/components/Origins/Editor';
import type { CopyWordSourceT, OriginT } from 'server/types';
import React, { useEffect, useState } from 'react';
import { useTranslations } from 'next-intl';
import { App, Button, Steps } from 'antd';
import {
  EnEntryTypesE,
  EnMeaningT,
  EnPartOfSpeechE,
  EnShortTranslationT,
  EnWordFormT,
  EnWordT,
} from 'server/types';
import { DefaultCommonData, DefaultShortTranslation } from './constants';
import { WordAlreadyExistBlock } from './components/WordAlreadyExistBlock';
import { CommonInfoDataT, StatusOfWordPresenceE } from './types';
import { Meanings } from './components/Meanings';
import { SubForms } from './components/SubForms';
import { CommonWordInfo } from './components/CommonWordInfo';
import { PreviewWord } from './components/PreviewWord';
import { ShortTranslations } from './components/ShortTranslations';
import { MeaningsTranslations } from './components/MeaningsTranslations';
import { getStepItems, prepareWordPayload } from './utils';
import { CheckWordBlock } from './components/CheckWordBlock';
import { EnApi } from '@/core/api/EnApi';
import { Title } from '@/core/ui/Title';
import styles from './styles.module.scss';
import { useWrittenByPeopleOnly } from '@/app/[locale]/(main-admin-content)/managing/_components/EditLicenseNote';

// Linked words pasted from an exported record: `{ word, part_of_speech }`
// objects, plain strings in older exports, or nothing at all
const headwordsOf = (links: unknown): string[] =>
  ((links || []) as Array<string | { word: string }>).map((s) => (typeof s === 'string' ? s : s.word));

export const EnWordForm: React.FC = () => {
  const t = useTranslations('en_managing_words');
  const tError = useTranslations('errors');
  const { message } = App.useApp();
  const [origins, setOrigins] = useState<OriginT[]>([]);
  const [copySource, setCopySource] = useState<CopyWordSourceT>();
  const [step, setStep] = useState<number>(0);
  const [stepItems, setStepItems] = useState(getStepItems(t, true));
  const [word, setWord] = useState<string>('');
  const [partOfSpeech, setPartOfSpeech] = useState<EnPartOfSpeechE | null>(null);
  const [type, setType] = useState<EnEntryTypesE>(EnEntryTypesE.word);
  const [commonInfo, setCommonInfo] = useState<CommonInfoDataT>(DefaultCommonData);
  const [shortTranslations, setShortTranslations] = useState<EnShortTranslationT[]>(DefaultShortTranslation);
  const [meanings, setMeanings] = useState<EnMeaningT[]>([]);
  const [forms, setForms] = useState<EnWordFormT[]>([]);
  const [statusOfPresence, setStatusOfPresence] = useState<StatusOfWordPresenceE>(
    StatusOfWordPresenceE.notChecked,
  );
  const [existingWordId, setExistingWordId] = useState<number | null>(null);
  const [isChecking, setIsChecking] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const writtenByPeopleOnly = useWrittenByPeopleOnly();
  const addWord = async () => {
    if (isSubmitting || !word.trim() || !partOfSpeech) {
      return;
    }
    setIsSubmitting(true);
    try {
      const body: EnWordT = {
        ...commonInfo,
        // a dataset of a public source takes nothing generated by a model (issue #531)
        ...(writtenByPeopleOnly && { generated: false, generated_by_model: '' }),
        word: word.trim(),
        part_of_speech: partOfSpeech,
        meanings,
        // Untouched default rows are dropped the same way as blank word forms
        short_translations: shortTranslations.filter(
          (s) => s.description.trim().length > 0 || s.variants_of_words.length > 0,
        ),
        forms: type === EnEntryTypesE.word ? forms.filter((c) => c.word.trim().length > 0) : [],
      };
      const res = await EnApi.addWord({
        ...prepareWordPayload(body),
        origins,
        ...(copySource && { copy_source: copySource }),
      });
      if ('error' in res) {
        const mes = tError(res.message);
        message.error(mes);
      } else {
        const mes = t('added_success');
        message.success(mes);
        setWord('');
        setOrigins([]);
        setCopySource(undefined);
        setStatusOfPresence(StatusOfWordPresenceE.notChecked);
        setExistingWordId(null);
        setShortTranslations(DefaultShortTranslation);
        setPartOfSpeech(null);
        setCommonInfo(DefaultCommonData);
        setForms([]);
        setMeanings([]);
        setStep(0);
        setStepItems(getStepItems(t, true));
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'unknown_error';
      message.error(tError(errorMessage));
    } finally {
      setIsSubmitting(false);
    }
  };

  const checkWord = async () => {
    if (isChecking || !word.trim() || !partOfSpeech) {
      return;
    }
    setIsChecking(true);
    try {
      const res = await EnApi.checkWord(word.trim(), partOfSpeech);

      if ('error' in res) {
        message.error(tError(res.message));
      } else {
        if (res.hasWord) {
          setStatusOfPresence(StatusOfWordPresenceE.present);
          setExistingWordId(res.id ?? null);
        } else {
          setStatusOfPresence(StatusOfWordPresenceE.absent);
          setExistingWordId(null);
          setStep(1);
          setStepItems(getStepItems(t));
          return true;
        }
      }
    } finally {
      setIsChecking(false);
    }
  };
  const insertJSON = async () => {
    try {
      const text = await navigator.clipboard.readText();
      const {
        meanings: parsedMeanings,
        forms: parsedForms,
        short_translations: parsedShortTranslations,
        word: _word,
        part_of_speech: _partOfSpeech,
        ...parsedCommonInfo
      } = JSON.parse(text) as EnWordT;
      setMeanings(
        (parsedMeanings || []).map((m: EnMeaningT, i: number) => ({
          ...m,
          id: i,
          // an exported word carries { word, part_of_speech } objects, older exports
          // plain strings or nothing; the form works with headwords
          synonyms: headwordsOf(m.synonyms),
          antonyms: headwordsOf(m.antonyms),
          translations: (m.translations || []).map((tr, ind: number) => ({ ...tr, id: ind })),
        })),
      );
      if (parsedForms) {
        setForms(parsedForms.map((f: EnWordFormT, i: number) => ({ ...f, id: i })));
      }
      // what is pasted is taken for the answer of a model — except into a dataset of a public source,
      // which holds what people wrote (issue #531)
      setCommonInfo({ ...parsedCommonInfo, generated: !writtenByPeopleOnly });
      if (parsedShortTranslations) {
        setShortTranslations(parsedShortTranslations);
      }
    } catch {
      message.error(t('invalid_json'));
    }
  };

  const prefill = (source: CopyPreviewT) => {
    const {
      word: spelling,
      part_of_speech: pos,
      meanings: senses,
      forms: inflections,
      short_translations: translations,
      origins: sources,
      copy_source,
      licenses: _licenses,
      contributions: _contributions,
      user_modified: _modified,
      ...common
    } = source;
    setWord(spelling);
    setType(
      pos === EnPartOfSpeechE.phrase
        ? EnEntryTypesE.phrase
        : pos === EnPartOfSpeechE.grammar_pattern
          ? EnEntryTypesE.grammar_pattern
          : EnEntryTypesE.word,
    );
    setPartOfSpeech(pos);
    setCommonInfo(common);
    setMeanings(senses);
    setForms(inflections);
    setShortTranslations(translations);
    setOrigins(sources ?? []);
    setCopySource(copy_source);
    setStatusOfPresence(StatusOfWordPresenceE.notChecked);
    setStep(0);
  };

  const onClickCommonNext = () => setStep(2);
  const onClickFormsNext = () => setStep(3);
  const onClickMeaningsNext = () => setStep(4);
  const onClickShortNext = () => setStep(5);
  const onClickMeaningTranslationNext = () => setStep(6);

  useEffect(() => {
    if (copySource) return;
    if (type === EnEntryTypesE.word) {
      setPartOfSpeech(null);
    }
    if (type === EnEntryTypesE.phrase) {
      setPartOfSpeech(EnPartOfSpeechE.phrase);
    }
    if (type === EnEntryTypesE.grammar_pattern) {
      setPartOfSpeech(EnPartOfSpeechE.grammar_pattern);
    }
  }, [type, copySource]);
  return (
    <div className={styles.addWordForm}>
      <div className={styles.leftContainer}>
        {step > 0 && (
          <div className={styles.selectedWordTitle}>
            <Title level={5}>{word}</Title>
            <Title level={5}>-</Title>
            <Title level={5}>{partOfSpeech}</Title>
          </div>
        )}
        <Steps
          className={styles.steps}
          orientation="vertical"
          type="dot"
          current={step}
          onChange={setStep}
          items={stepItems}
        />
        {step > 0 && (
          <Button onClick={insertJSON} type="primary">
            {t('insert_json')}
          </Button>
        )}
      </div>
      <div className={styles.content}>
        {step > 0 && <OriginsEditor context="word" value={origins} onChange={setOrigins} />}
        {step === stepItems.length - 7 && (
          <>
            <CopyWordPicker onCopy={prefill} />
            <CheckWordBlock
              checkWord={checkWord}
              checking={isChecking}
              word={word}
              type={type}
              setType={setType}
              setWord={setWord}
              setPartOfSpeech={setPartOfSpeech}
              partOfSpeech={partOfSpeech}
            />
            {statusOfPresence === StatusOfWordPresenceE.present && (
              <WordAlreadyExistBlock word={word} wordId={existingWordId} />
            )}
          </>
        )}
        {step === stepItems.length - 6 && (
          <CommonWordInfo
            onChange={setCommonInfo}
            commonInfo={commonInfo}
            pos={partOfSpeech as EnPartOfSpeechE}
            clickNext={onClickCommonNext}
          />
        )}
        {step === stepItems.length - 5 && (
          <SubForms
            setSubForms={setForms}
            subForms={forms}
            onClickFormsNext={onClickFormsNext}
            pos={partOfSpeech as EnPartOfSpeechE}
          />
        )}
        {step === stepItems.length - 4 && (
          <Meanings
            onClickNext={onClickMeaningsNext}
            meanings={meanings}
            setMeanings={setMeanings}
            headword={word}
          />
        )}
        {step === stepItems.length - 3 && (
          <ShortTranslations
            onClickNext={onClickShortNext}
            shortTranslations={shortTranslations}
            setShortTranslations={setShortTranslations}
          />
        )}
        {step === stepItems.length - 2 && (
          <MeaningsTranslations
            meanings={meanings}
            setMeanings={setMeanings}
            onClickNext={onClickMeaningTranslationNext}
          />
        )}
        {step === stepItems.length - 1 && (
          <PreviewWord
            word={{
              ...commonInfo,
              meanings,
              forms: type === EnEntryTypesE.word ? forms : [],
              short_translations: shortTranslations,
              part_of_speech: partOfSpeech as EnPartOfSpeechE,
              word,
            }}
            addWord={addWord}
            submitting={isSubmitting}
          />
        )}
      </div>
    </div>
  );
};
