name: check-pull-request

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

      - name: Prettier check
        run: yarn format:check

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Typecheck frontend
        run: yarn workspace frontend tsc --noEmit

      - name: Typecheck server
        run: yarn workspace server tsc --noEmit

  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Unit tests
        run: yarn test

      - name: Server e2e tests
        run: yarn workspace server test:e2e
