import { expect, test } from '@playwright/test';

import { SITE_API_URL } from '../config';

// Server-rendered word pages over the public API (issue #330); the data is
// the fixture dictionary seeded in site.setup.ts
test.describe('word pages', () => {
  test('a headword renders its entries from the fixture data', async ({ page }) => {
    await page.goto('/en/word/run');

    await expect(page.getByRole('heading', { level: 1, name: 'run' })).toBeVisible();
    // one seeded entry: the verb, with its meaning and the synonym link
    await expect(page.getByRole('heading', { level: 2, name: 'verb' })).toBeVisible();
    await expect(page.getByText('to move fast').first()).toBeVisible();
    await expect(page.getByRole('link', { name: 'sprint' })).toHaveAttribute('href', /\/en\/word\/sprint$/);
    // where the data comes from is a note over the entries (issue #538): the source,
    // the license, and the API call the page renders
    const note = page.getByRole('complementary', { name: 'Terms of the dictionary data' });
    await expect(note).toContainText('Source');
    await expect(note).toContainText('Vocab Bloom Hub English dataset');
    await expect(note.getByRole('link', { name: 'CC BY 4.0' })).toHaveAttribute(
      'href',
      '/en/docs/data-license',
    );
    await expect(note.getByRole('link', { name: 'AI-generated, may contain errors' })).toHaveAttribute(
      'href',
      '/en/docs/data',
    );
    await expect(note.getByText('GET /api/v1/words/run', { exact: true })).toBeVisible();
    const noteBox = await note.boundingBox();
    const entryBox = await page.locator('section').first().boundingBox();
    expect(noteBox!.y + noteBox!.height).toBeLessThanOrEqual(entryBox!.y);
    // one translation language at a time (issue #520): the fixture has Russian only, so it
    // shows by default, flagged, and there is nothing to pick from
    await expect(page.getByText('бежать').first()).toBeVisible();
    const flag = page.getByRole('img', { name: 'ru' }).first();
    await expect(flag).toBeVisible();
    // a picture the site serves, not an emoji: Windows has no glyphs for the flags (issue #538)
    await expect(flag).toHaveAttribute('src', '/flags/ru.svg');
    expect(await flag.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
    await expect(page.getByRole('group', { name: 'Language' })).toHaveCount(0);
  });

  // issue #531: the note under a word page leads to the terms of the data it shows
  test('the terms of the data are a page of the site', async ({ page }) => {
    await page.goto('/en/dataset-terms');

    await expect(page.getByRole('heading', { level: 1, name: 'Terms of the dictionary data' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'CC BY 4.0', exact: true })).toHaveAttribute(
      'href',
      'https://creativecommons.org/licenses/by/4.0/',
    );
    await expect(page.getByText('Generated by language models')).toBeVisible();
    // the project's own data is named by the link of its license: no notice to print in full
    await expect(page.getByTestId('license-text')).toHaveCount(0);

    // what the license asks of whoever takes the data further: the mark and the history are named
    const use = page.getByTestId('terms-of-use');
    await expect(use.getByRole('heading', { name: 'If you use this data' })).toBeVisible();
    await expect(use.getByRole('listitem')).toHaveCount(5);
    await expect(use).toContainText('carries modified: true');
    await expect(use).toContainText('GET /api/v1/words/{word}/history');
    // the terms are the ones of the served dataset; the read of every dataset states its own (issue #528)
    await expect(use).toContainText('GET /api/v1/words/{word}/datasets reads a word from every dataset');
    // CC BY 4.0 is not share-alike and has no notice to keep in full
    await expect(use).not.toContainText('share-alike');
    await expect(use.getByRole('link', { name: 'The terms in detail' })).toHaveAttribute(
      'href',
      '/en/docs/data-license#using-data-that-was-changed-on-an-instance',
    );

    await page.goto('/ru/dataset-terms');
    await expect(page.getByRole('heading', { name: 'Если вы используете эти данные' })).toBeVisible();
  });

  // issue #531: the fixture words are made through the admin API — they are
  // the owner's, not what a source says, and the page tells the reader
  test('an entry made on the instance says that it was changed or added by its owner', async ({
    page,
    request,
  }) => {
    await page.goto('/en/word/run');
    await expect(page.getByTestId('entry-modified')).toHaveText('changed or added by the owner of this site');

    await page.goto('/ru/word/run');
    await expect(page.getByTestId('entry-modified')).toHaveText('изменено или добавлено владельцем сайта');

    const api = await request.get(`${SITE_API_URL}/v1/words/run`);
    expect((await api.json()).data[0]).toEqual(expect.objectContaining({ modified: true }));
  });

  // issue #531: not only that an entry was changed, but what was, and who sent the correction
  test('the page of an edited word says what was changed', async ({ page, request }) => {
    await page.goto('/en/word/sprint');

    const history = page.getByTestId('word-history');
    await expect(history.locator('summary')).toHaveText('What was changed on this site');
    await history.locator('summary').click();
    await expect(history.getByRole('link', { name: 'What this means if you use the data' })).toHaveAttribute(
      'href',
      '/en/dataset-terms',
    );
    const items = history.getByTestId('word-history-item');
    await expect(items).toHaveCount(2);

    // the latest first: the correction, then the word as it was added
    await expect(items.nth(0)).toContainText('Entry: changed');
    await expect(items.nth(0).getByTestId('word-history-author')).toHaveText(
      'a correction sent by Ada Lovelace',
    );
    await expect(items.nth(0)).toContainText('description');
    await expect(items.nth(0).locator('ins')).toHaveText('to run at full speed for a short distance');
    await expect(items.nth(0).locator('del')).toHaveText('—');
    await expect(items.nth(1)).toContainText('Entry: added');
    await expect(items.nth(1).locator('dl')).toHaveCount(0);

    await page.goto('/ru/word/sprint');
    await expect(page.getByTestId('word-history').locator('summary')).toHaveText('Что изменено на этом сайте');

    const api = await request.get(`${SITE_API_URL}/v1/words/sprint/history`);
    const { data, meta } = await api.json();
    expect(meta).toEqual({ word: 'sprint', count: 2, variants: [] });
    expect(data[0]).toEqual(
      expect.objectContaining({
        origin: 'suggestion',
        author: 'Ada Lovelace',
        entity: 'word',
        action: 'update',
      }),
    );
  });

  // "Polish" and "polish" are two words: two pages, each with its entries and its own history
  test('spellings that differ by case are pages of their own', async ({ page }) => {
    const upper = await page.goto('/en/word/Polish');
    expect(upper?.status()).toBe(200);
    await expect(page).toHaveURL(/\/en\/word\/Polish$/);
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Polish');
    await expect(page.getByRole('heading', { level: 2 })).toHaveText(['noun']);
    // the description of the entry; the history under it holds the same words, folded
    await expect(page.getByText('the language spoken in Poland').first()).toBeVisible();
    await expect(page.getByTestId('other-spellings').getByRole('link', { name: 'polish' })).toHaveAttribute(
      'href',
      '/en/word/polish',
    );

    await page.goto('/en/word/polish');
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('polish');
    await expect(page.getByRole('heading', { level: 2 })).toHaveText(['verb']);
    await expect(page.getByText('the language spoken in Poland')).toHaveCount(0);
    await expect(page.getByTestId('other-spellings').getByRole('link', { name: 'Polish' })).toBeVisible();

    // a spelling the dictionary does not hold as it is leads to the lower-case one
    await page.goto('/en/word/POLISH');
    await expect(page).toHaveURL(/\/en\/word\/polish$/);
    // …and where the dictionary holds one spelling, the case never mattered
    await page.goto('/en/word/Sprint');
    await expect(page).toHaveURL(/\/en\/word\/sprint$/);
    await expect(page.getByTestId('other-spellings')).toHaveCount(0);
  });

  // every part of speech has the block of its own edits, under the entry they were made in
  test('the edits of an entry are shown under that entry', async ({ page }) => {
    await page.goto('/en/word/Polish');
    const entry = page
      .locator('section')
      .filter({ has: page.getByRole('heading', { level: 2, name: 'noun' }) });
    const history = entry.getByTestId('word-history');
    await expect(history.locator('summary svg')).toHaveCount(1);
    await history.locator('summary').click();
    const items = history.getByTestId('word-history-item');
    await expect(items).toHaveCount(2);
    await expect(items.nth(0).locator('del')).toHaveText('the language of Poland');
    await expect(items.nth(0).locator('ins')).toHaveText('the language spoken in Poland');

    // "run" is a verb and a noun, each added on the instance: a block under each, none for the page as a whole
    await page.goto('/en/word/run');
    await expect(page.getByTestId('word-history')).toHaveCount(
      await page.getByRole('heading', { level: 2 }).count(),
    );
    for (const block of await page.getByTestId('word-history').all()) {
      await block.locator('summary').click();
      await expect(block.getByTestId('word-history-item')).toHaveCount(1);
    }
  });

  // issue #480: the Russian copy leads with the Russian translation — in the
  // title, the description and on the first screen
  test("a word page in a translated locale leads with that locale's translations", async ({ page }) => {
    await page.goto('/ru/word/run');

    await expect(page).toHaveTitle('run — перевод: бежать · Vocab Bloom Hub');
    await expect(page.locator('meta[name="description"]')).toHaveAttribute(
      'content',
      'Перевод слова run на русский: бежать. definition of to move fast',
    );
    await expect(page.getByText('Перевод: бежать')).toBeVisible();
    // …and the entry's own short translation is in the open
    await expect(page.getByText('бежать').nth(1)).toBeVisible();
    // the English copy has no such lead
    await page.goto('/en/word/run');
    await expect(page).toHaveTitle('run — meanings, forms, translations · Vocab Bloom Hub');
    await expect(page.getByText('Translation:')).toHaveCount(0);
  });

  // issue #538: the suite's API holds one dataset, helpers/site-datasets-stub.mjs adds
  // a second one to "run" and makes "footrace" a word of that second dataset alone
  test('a headword one dataset holds has no tabs', async ({ page }) => {
    await page.goto('/en/word/abandon');

    await expect(page.getByRole('heading', { level: 2, name: 'verb' })).toBeVisible();
    await expect(page.getByTestId('dataset-tabs')).toHaveCount(0);
  });

  test('a headword of two datasets has a tab for each, the one of the project open', async ({ page }) => {
    await page.goto('/en/word/run');

    const tabs = page.getByRole('tablist', { name: 'Datasets' }).getByRole('tab');
    await expect(tabs).toHaveText(['Vocab Bloom Hub English dataset', 'Open English WordNet']);
    await expect(tabs.nth(0)).toHaveAttribute('aria-selected', 'true');
    const served = page.getByText('definition of to move fast');
    const second = page.getByText('definition of a race run on foot');
    await expect(served).toBeVisible();
    // the page holds the dataset of its first tab and no other
    await expect(second).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Report a mistake' })).toBeVisible();

    // the dataset of another tab is read by the browser when the tab is pressed
    const read = page.waitForResponse((response) => response.url().endsWith('/api/v1/words/run/datasets'));
    await tabs.nth(1).click();
    expect((await read).status()).toBe(200);
    await expect(tabs.nth(1)).toHaveAttribute('aria-selected', 'true');
    await expect(second).toBeVisible();
    await expect(served).toBeHidden();
    // the choice is no part of the URL
    await expect(page).toHaveURL(/\/en\/word\/run$/);
    const panel = page.getByRole('tabpanel', { name: 'Open English WordNet' });
    await expect(panel.getByRole('heading', { level: 2 })).toHaveText(['noun']);
    // the pronunciation next to the headword is the one of the open dataset
    await expect(page.getByText('/second/').first()).toBeVisible();
    await expect(page.getByText('/rʌn/').first()).toBeHidden();
    // the terms are the dataset's own, and its read is named
    const terms = panel.getByTestId('dataset-terms');
    await expect(terms).toContainText('Open English WordNet');
    await expect(terms).toContainText('GET /api/v1/words/run/datasets');
    await expect(terms.getByRole('link', { name: 'CC BY 4.0' })).toHaveAttribute(
      'href',
      'https://creativecommons.org/licenses/by/4.0/',
    );
    await expect(terms.getByRole('link', { name: 'Open English WordNet' })).toHaveAttribute(
      'href',
      'https://en-word.net',
    );
    await expect(terms.getByText('The notice of the second dataset, in full.')).toBeAttached();
    // a report goes to the queue of the served dataset
    await expect(page.getByRole('button', { name: 'Report a mistake' })).toBeHidden();
    await expect(panel.getByRole('link', { name: 'footrace' })).toHaveAttribute('href', '/en/word/footrace');

    // the keys of a tab list; what the server rendered was kept, nothing is read again
    await tabs.nth(1).press('ArrowLeft');
    await expect(tabs.nth(0)).toBeFocused();
    await expect(tabs.nth(0)).toHaveAttribute('aria-selected', 'true');
    await expect(served).toBeVisible();
    await expect(page.getByText('/rʌn/').first()).toBeVisible();
  });

  test('a fork labels its sources and shows contribution terms only under the edited word', async ({
    page,
  }) => {
    // The second tab is an API fixture: PostgreSQL suites verify the stored
    // snapshots; here the browser consumes those fields on a lazily loaded tab.
    await page.route('**/api/v1/words/run/datasets', async (route) => {
      const response = await route.fetch();
      const body = await response.json();
      const original = body.data[0].entries[0];
      original.origins[0].acquisitions = [
        {
          id: 'intermediate-copy',
          method: 'copy',
          recorded_at: '2026-10-03T12:00:00.000Z',
          via: { name: 'Intermediate fork', version: '1.2', url: 'https://example.org/intermediate' },
        },
      ];
      const contribution = {
        ...original.origins[0],
        id: 'contribution:example',
        name: 'Example fork',
        version: null,
        attribution: 'Example fork editors',
        url: 'https://example.org/fork',
        notices: [],
        licenses: [
          {
            spdx: 'ODbL-1.0',
            name: 'Open Database License',
            url: 'https://opendatacommons.org/licenses/odbl/1-0/',
          },
        ],
      };
      body.data[1] = {
        ...body.data[1],
        title: 'Example fork',
        description: 'A test fork description',
        origins: original.origins,
        license: 'ODbL-1.0',
        license_url: contribution.licenses[0].url,
        count: 2,
        entries: [
          { ...original, id: 900010, part_of_speech: 'noun', modified: false, contributions: [] },
          { ...original, id: 900011, part_of_speech: 'verb', modified: true, contributions: [contribution] },
        ],
      };
      await route.fulfill({ response, json: body });
    });
    await page.goto('/en/word/run');
    await page.getByRole('tab', { name: 'Open English WordNet' }).click();
    const panel = page.getByRole('tabpanel', { name: 'Open English WordNet' });
    await expect(panel.getByRole('heading', { name: 'Dataset sources' })).toBeVisible();
    await expect(panel.getByText('Dataset description: A test fork description')).toBeVisible();
    const unchanged = panel.getByTestId('entry-900010');
    const changed = panel.getByTestId('entry-900011');
    await expect(unchanged.getByTestId('entry-modified')).toHaveCount(0);
    await expect(unchanged.getByText('ODbL-1.0')).toHaveCount(0);
    const unchangedSources = unchanged.getByRole('region', { name: 'Sources and licenses', exact: true });
    await unchangedSources.locator('summary').first().click();
    await expect(unchangedSources.getByText('Copied from Intermediate fork · 1.2')).toBeVisible();
    await expect(unchangedSources.locator('a[href="https://example.org/intermediate"]')).toBeVisible();
    await expect(changed.getByTestId('entry-modified')).toBeVisible();
    const terms = changed.getByRole('region', { name: 'Changes and their licenses' });
    await expect(terms.locator('summary')).toContainText('Edited in Example fork');
    await expect(terms.locator('summary')).toContainText('ODbL-1.0');
    await terms.locator('summary').click();
    await expect(terms.getByRole('link', { name: 'ODbL-1.0' })).toHaveAttribute(
      'href',
      'https://opendatacommons.org/licenses/odbl/1-0/',
    );
    await expect(terms.getByText('Example fork editors')).toBeVisible();
    const originals = changed.getByRole('region', { name: 'Sources and licenses', exact: true });
    await originals.locator('summary').first().click();
    await expect(originals.getByRole('link', { name: 'CC-BY-4.0' })).toBeVisible();
  });

  test('the page that is sent is the first tab, rendered by the server and cacheable', async ({ request }) => {
    const response = await request.get('/en/word/run');

    expect(response.status()).toBe(200);
    const html = await response.text();
    expect(html).toContain('definition of to move fast');
    expect(html).toContain('Open English WordNet');
    // the dataset of the other tab is named, not sent
    expect(html).not.toContain('definition of a race run on foot');
    expect(response.headers()['cache-control']).toBe('s-maxage=3600, stale-while-revalidate=86400');
    // a dataset is no part of the URL: a query changes nothing
    const asked = await request.get('/en/word/run?dataset=wordnet');
    expect(await asked.text()).not.toContain('definition of a race run on foot');
  });

  test('a headword only another dataset holds is a page, kept out of the search index', async ({ page }) => {
    const response = await page.goto('/en/word/footrace');

    expect(response?.status()).toBe(200);
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('footrace');
    await expect(page.getByText('definition of a race between people who run')).toBeVisible();
    await expect(page.getByTestId('dataset-tabs')).toHaveCount(0);
    await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', /noindex/);
    await expect(page.getByRole('button', { name: 'Report a mistake' })).toHaveCount(0);
  });

  test('the word index offers the search and the examples', async ({ page }) => {
    await page.goto('/en/word');

    const search = page.getByRole('search').first();
    await search.getByRole('searchbox').fill('run');
    await search.getByRole('button', { name: 'Search' }).click();
    await expect(page.getByRole('link', { name: 'run', exact: true }).first()).toBeVisible();
    // the term lands in the URL so the search can be shared (issue #399)
    await expect(page).toHaveURL(/\?q=run$/);
  });

  test('opening a ?q= link restores the search (issue #399)', async ({ page }) => {
    await page.goto('/en/word?q=sprint');

    await expect(page.getByRole('searchbox')).toHaveValue('sprint');
    await expect(page.getByRole('link', { name: 'sprint', exact: true }).first()).toBeVisible();
  });

  test('a missing headword answers 404', async ({ page }) => {
    const response = await page.goto('/en/word/no-such-headword');

    expect(response?.status()).toBe(404);
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Page not found');
  });

  test('/word/random redirects to a headword', async ({ request }) => {
    const response = await request.get('/en/word/random', { maxRedirects: 0 });

    expect(response.status()).toBe(307);
    // relative: behind a reverse proxy the server does not know its public origin
    expect(response.headers()['location']).toMatch(/^\/en\/word\/.+$/);
  });

  test('the edit mode of the report form files a form proposal (issue #327)', async ({ page }) => {
    await page.goto('/en/word/abandon');

    // one entry point: the report button, then the edit-the-entry mode
    await page.getByRole('button', { name: 'Report a mistake' }).click();
    const form = page.getByRole('form', { name: 'Report a mistake' });
    await form.getByRole('button', { name: 'Edit the entry' }).click();

    // the full word form opens prefilled; only the changed values are sent
    await form.getByLabel('Description').fill('to leave somebody or something behind for good');
    await form.getByRole('button', { name: 'Suggest the changes' }).click();

    await expect(page.getByText('Thank you — the proposal is in the moderation queue.')).toBeVisible();
  });

  test('a too-short text report shows a validation message instead of doing nothing (issue #351)', async ({
    page,
  }) => {
    await page.goto('/en/word/run');

    await page.getByRole('button', { name: 'Report a mistake' }).click();
    const form = page.getByRole('form', { name: 'Report a mistake' });
    await form.getByRole('textbox', { name: 'What is wrong' }).fill('too short');
    await form.getByRole('button', { name: 'Send the report' }).click();

    await expect(page.getByText('Please describe the mistake in at least 10 characters.')).toBeVisible();
  });

  test('the report form files a suggestion into the instance queue (issue #327)', async ({ page }) => {
    await page.goto('/en/word/run');

    await page.getByRole('button', { name: 'Report a mistake' }).click();
    const form = page.getByRole('form', { name: 'Report a mistake' });
    await form
      .getByRole('textbox', { name: 'What is wrong' })
      .fill('The definition of "to move fast" misses that it is on foot — e2e report.');
    await form.getByRole('button', { name: 'Send the report' }).click();

    await expect(page.getByText('Thank you — the report is in the moderation queue.')).toBeVisible();
  });

  // issue #531: a name is published with the correction, so it is taken with the sender's word only
  test('a sender is named only when they agree to it', async ({ page }) => {
    await page.goto('/en/word/run');

    await page.getByRole('button', { name: 'Report a mistake' }).click();
    const form = page.getByRole('form', { name: 'Report a mistake' });
    await form
      .getByRole('textbox', { name: 'What is wrong' })
      .fill('The example of "to move fast" has a typo — e2e report with a name.');
    // nobody is asked to agree to anything before they give a name
    await expect(form.getByRole('checkbox')).toHaveCount(0);
    await form.getByRole('textbox', { name: /Your name/ }).fill('Ada Lovelace');
    await form.getByRole('button', { name: 'Send the report' }).click();
    await expect(page.getByText('Tick the box to be named, or leave the name empty.')).toBeVisible();

    await form.getByRole('checkbox', { name: /Show this name next to the correction/ }).check();
    await form.getByRole('button', { name: 'Send the report' }).click();
    await expect(page.getByText('Thank you — the report is in the moderation queue.')).toBeVisible();
  });
});
